
CREATE TABLE IF NOT EXISTS `suppliers` (
	`supplier_id` INT(11) NOT NULL AUTO_INCREMENT,
	`supplier_name` VARCHAR(150) NOT NULL,
	`contact` VARCHAR(100) DEFAULT NULL,
	`email` VARCHAR(150) DEFAULT NULL,
	`address` TEXT DEFAULT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`supplier_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
